// <auto-generated />
using Discount.Grpc.Data.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20241016213212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Discount.Grpc.Models.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150m,
                            Description = "IPhone Discount",
                            ProductName = "IPhone X"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100m,
                            Description = "Samsung Discount",
                            ProductName = "Samsung 10"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50m,
                            Description = "Huawei Discount",
                            ProductName = "Huawei P30"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 75m,
                            Description = "Xiaomi Discount",
                            ProductName = "Xiaomi Mi 10"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 200m,
                            Description = "IPhone Discount",
                            ProductName = "IPhone 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
